page_group: uk_london_id_1_binjal
account_name: Binjal Mehra
country_code: GB
target_location: London, United Kingdom
require_uk_ip: true
ai_disclosure_status: pending_determination
delete_after_post: true
database:
  path: data/posted_videos.db
retry:
  max_attempts: 3
  base_delay_seconds: 5
  max_delay_seconds: 60
notifications:
  discord_enabled: false
  discord_webhook_url: ''
pages:
- page_id: '1275440552308410'
  name: uk1_page_1
  display_name: Bitter Lullaby
  enabled: true
  drive_folder_id: 17SQXMG8HL8tGgXI1-Tn5I5mQ8Ce0h0a2
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSnx29fEdMshkDiACyu2R8dGHbBWwlG7bbsI9MrACx3t0WZBwdj0jLx6gZAwGg4p5BX3GMO821dZCbLL1QGDZBUXqzs7NRWZBhXo8HgyNZBV1ZBJxGZCi3yhjyUTj3xpgnljYYbGed34XpOFV6FvvxkgjE5zl06zUWFhIui0TfDo95APXLBcvNZANa8lbu
- page_id: '1094091620443741'
  name: uk1_page_2
  display_name: Apex Dominion
  enabled: true
  drive_folder_id: 1hhkz2KlqkCJ7wpbgKk4ya_361AtlAjvw
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSnK0zNVDyP8tuwnwvAHfsoNQOrfwPG2b2wqLkJGsx015jgdodqZByYC3YPtZAwUYeP69ANIQufHfLhw5mt3pzDDsbNgXN7LTem1IHZBTHk5kPbyXUtYwIQsuSCgDbZCeHg97eZCD5q7tb2OmHdZC9xkx7mtGkg9VdD28DvhZAth0CfyrtloW7FMF5dO
- page_id: '883030611569420'
  name: uk1_page_3
  display_name: Apex Narrative
  enabled: true
  drive_folder_id: 1vTdVLboxrjH3lRqCDChX6r0MvlOW_6xZ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSmdcrOMUrnvBmz7yt3kFvZCNZAKWbGFW4Tfus3BECkthWMZCZBDZCHQgdxMpo122oVVb0YsNdTam9BjEztqbJEkef2VAuw2DF0WBPlV1fcAGC4HU7SMKUzbZCvqMStKx7pOKR2ZCzX1E3wE6QGly4to7zVzxaHcuCAddEkbvmHZCQmKvapPFyE8ZBKqme
- page_id: '876743625532242'
  name: uk1_page_4
  display_name: Young  Bradley
  enabled: true
  drive_folder_id: 1PBRUGAoXqpmr_2L6YuxkVACX3LBEFJiE
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSkY5P2Cl5Qt96Yb8qVbKnFydtcELOxCcagCMKCiqf5R7uEDHOJjcUicZAd3W4GrGKduTZB12hGZBq6zRwsFogyUcUPFxsfYjN23qRwRJzDeIRwZCeLevEo98zGBogTcGi3F0IJbR1GAbOtwZCuW0VZBAWT7UlGNlwRRBlZBOFbearg5Q7UZAMlQLssOr
- page_id: '954228904442447'
  name: uk1_page_5
  display_name: Scott  Dennis
  enabled: true
  drive_folder_id: 1JmtVwNgjy0ze94TaUe3_a1GKxZKmh7oY
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSpznoNsSxVpEpGcpXptbzhFtYjQtUmarNjtEAoRAzOIWmMuqWCGWyjDDX4VINgnkpIjce8SMPdhfjimpxsf4sVQu82azifjqXGOW8Sel8fxZBvllBwkQB7v2B0KorUkZBkcCjJF6ivgltie8c1CdPRk5SS0m2g1oySiZC5x1Jx7DZARrja9T2foP
- page_id: '884416694753956'
  name: uk1_page_6
  display_name: Wood  Stephen
  enabled: true
  drive_folder_id: 1Z9Ov642iD-iilWbIVOm0b-jdbFbDNdoB
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSiwg1Q2NSN0Al8idgY3kOOQr9FNDKhZADTHYWLWFtu8H4wfHJZAob5pieGbXc5DxMiH59pkH2y0XhSnjEjGVyBiBgcZBZANylbGKZAgJ1ZAPDZChnxkCoZCuxa9KWwC0i2FStHyXZBZC8txLOzSjEO5xGAKDyQd3QdNfpeX996My1UQGFcY2cpD5rUMQZCV
- page_id: '766333629906067'
  name: uk1_page_7
  display_name: Morgan  Donald
  enabled: true
  drive_folder_id: 1ISgWlF4cUFvRzDhyqRf7n41UGNSqBHlP
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSswIY92qHmoj6N3TS6akMBgA66YexkiaOi89QlZBlNRA0BYq8d7HdZBPO2CoejXTZBR7VzLo6fSsjGYXxhMbuE5YbFVYTeAjkFtEuED4iSz4j0G721fzxCZBdFD0AL32gCs47LOoMw0yylcPYZBvBwYEBKkxrWX28onCXlrP3vJgnSTDqGhRT2ZBmo
- page_id: '838517782676673'
  name: uk1_page_8
  display_name: Rogers  Albert
  enabled: true
  drive_folder_id: 1zkNs_XzwXhiElCQimHdHxORUnJnPLXSJ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSojKWcYqVARMdicEwncJExda7vxHhM8CAKPRF5jY9A5eNGl2mqu479HdKYTYfwuqdGy4iUZCAqu8qAqzMlNUYZAYZBeV0XzDkr7ubV70fjonIoqpN7hfvis5WMy5ZBU9SpS6za71C9n1EMRTP0f54vmNEXjL4XT8CtZA5vlfHFyiPDrl9v5fiLguZC
- page_id: '860013240524658'
  name: uk1_page_9
  display_name: Roberts  Austin
  enabled: true
  drive_folder_id: 1gm2neO5u2CWo-xBUP1nN507GUeoSqmRk
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSpQ9c4TpUgMZC9Fyws6WUi41K9j3mCiC9c6JkONhzJgrp1sXVJb6mZAdTSrtWOegMGPFxohe1HWgpurYmXN7uZBOB4QXVDf72VFOnioZBQBr6hWuqx7h7VZB1HRx7ZBE8LxdzctDprLNoq26IlXyA6M6RLsUYRdKRZBlo4ITgLC7MT3vXUQp7JFif1R
- page_id: '802792259592614'
  name: uk1_page_10
  display_name: Mitchell  Jack
  enabled: true
  drive_folder_id: 1hOeE4b28ph5m5QiTvYZyQ8Mduc8bLhbO
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSr40PqfV3ATX5D4lQPwTJeHVSwAyiHLZCDDZABUrUVh9TdcRAlchhZBy67By7dVahINSsVaNl547qbe9Mgkh48UyeIIOQU8zBAYupSdIuDzSlFNHBIlAu1JfeJmJjo40rbQUXB8D5b6VVZANMSTqrY8YLG15ZCx39DHgZCaIPaYV0dnpsZC2pIHkbeE
- page_id: '439151942618231'
  name: uk1_page_11
  display_name: Words Though
  enabled: true
  drive_folder_id: 1BpkOd2UoI5-XbRvdVmaL2m3KJGO5ci29
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBStpb29za2QdjbAHvfR9SoG91uUdoB9GhCf2azGGZBD5TaX8Ii26z6SXyHPrsCVSZC6ocfz2HJNJIWCZAJFy0ZAlMQ1qkPZCMX0YdbEwtVUsBVOdBkLaBmoZAKsk1zFjkE0t9okQZBZAZA2T2kZBb5182sUI1AoCJtLPk4I1YITP6k5C6ZAINPx7ZCJXf6X5Y
- page_id: '297665506763102'
  name: uk1_page_12
  display_name: Quantum Collective
  enabled: true
  drive_folder_id: 1DiHP1KqZXnPqlIghqDiyk1_733vzUmtM
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAMQQKyfacIBSvhuZCFFpUj7duZCxvZCZAk6UFOSFXM1H7agRVJF1GaQZBRZCLWkvF6bfiPpFQC5YIR3cCzDoJmPuUmg6LzU4A4phCWC9ttps7isMoJHRIzOZAQrNQiimz5j9yk0GnCQF9yI7jva9TJT8U4A6wG3keGx7Q40xh35nRS9A1UMnHEj4k4L8IttOBjQMg7
