page_group: usa_account_3_radika
account_name: Radika Patel
country_code: US
target_location: United States
require_uk_ip: false
ai_disclosure_status: pending_determination
delete_after_post: true
database:
  path: data/posted_videos.db
retry:
  max_attempts: 3
  base_delay_seconds: 5
  max_delay_seconds: 60
notifications:
  discord_enabled: false
  discord_webhook_url: ''
pages:
- page_id: '1033900793135926'
  name: page_31
  display_name: Cloud berry Lane
  enabled: true
  drive_folder_id: 1gtFrX3Ji1yjJ5f8yHe1zOcdgMCTDQFMn
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSifag2ZCDwjE94ZCOFPZBoxDp9lUHG98MkhodnzzkPN5HAvqi8sbHxbiiewDqI8VTUinOe1L6SUlo2FV2IVP1s8FDTwayMSkUUrfSupQqdbSRT5ylDNPermg6dqbJq0txUpXDpdXPFQAjEaiq56tuBUv4iKdjt4D38Ce85LgTCZAhLaTvIblcavQ7u5R
- page_id: '984876688045322'
  name: page_32
  display_name: Sunset Mint Post
  enabled: true
  drive_folder_id: 1BURCLnzpluribfLIMlx7iPp-qdf_GL2T
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSp8UmLmrjZAEhrCu5hZCHlfujzLaPz4iI9alJrQg8OZCy1kVJYKPXsPo79g93qc3NZAq0LZBTHN3KMdjwYxFAvrUvuycKNco3pnXKZCol6JySgJ1NtwZCRWWExZA2MZBgYHNzzfoISYSHhPdM4ULcwRiB5MZCR9azfhC1v5nvANIdh2bsih76ZCSqN1aJR2xADD
- page_id: '928116440385651'
  name: page_33
  display_name: Timeless Glimpse
  enabled: true
  drive_folder_id: 1TcsGrKQd3ueOdVGgjsG5ujrwHmnoLd4N
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSifZBTx7A3nzbAI3ZAff7TTOw0uqZBdJ52fZB6GZAiKenFAP7h7tARY4SRTtbDZCrRhXlqUZCEELD1qZCGqtYsZCzPY93HeJsgQZAIZAZCzxDXsmHREopN1L1Q1voXv9ySbeyIZBz1hwnzXRS3XfDEuZBVye4ZBTtP76tbjVNI0oWdimmdfnlUtE2PcmSmXvNcuxj5Q
- page_id: '495281633679562'
  name: page_34
  display_name: The Entertainment Zone
  enabled: true
  drive_folder_id: 1pBBPnxX539_8XbACP_xN5ZaqdgnVNdaC
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSgrTespvrdaHMenhyBbVwzfwm5zw3dxNw7WyVDqjOy0K96SgGnENSXyCZBvCMERwX9y1rYeXNZCwB09vMbsKjrkB6VrlA5LDkqgOuZBif1d9IEGAkpPjfjOx6pZBMLy7xtpUfwZC0KTlgxVlRQrGFZCQf3w2UrLOy6TELeq8cs9toW7e8NSIXtYvzBXsZAF
- page_id: '461899523680517'
  name: page_35
  display_name: House Note
  enabled: true
  drive_folder_id: 1MMHC7iT-E1r-R8p-uSXY5_JJU5ttxhAp
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSsHvYvIjfiaijeahymBz333FtQCHt8C03kDR1o62TudY7y7gjmkazg5rLZBOrjwgblXCPhaDDXKv8b4hNb4xzLuTcnUjUZBjVW7scw3JZBroHleKDyXaoIF6piM4lbZAwFpZCexZBw5MNksW9lF0ABEqktSOG6frO4bp1fqfWSNBcZBpze8xoIBrQraPbMV
- page_id: '512339515286069'
  name: page_36
  display_name: Wand Wizardry Legend
  enabled: true
  drive_folder_id: 12Z5ghscmqcwCCjqK4nE-AEa0ecwPmBxA
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSmmZAREkPz39sSZBrLGZA6fppXci675LQx7z6tLcu2HVRxtuGKrOPDsmXZBd9VMDJpNAtU0ugkABbvnet4cvfKFHkn6qSZBiHs9TJOw2gJLnyqJrKRli0CCWtZByUScCpRTZAuIQpmuE6IxxXIoWeHghjyJWc3Y35uATPEPzXp0HktQWhR4DJXcw8Kkq02k
- page_id: '481027178422627'
  name: page_37
  display_name: Potato Flamingo
  enabled: true
  drive_folder_id: 11EFX0WJ32MzLCMbtRU3cehqjmFLuQ3KC
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSj2duSAEsZBUc47i07FZArbAWgDZAZCcoWvTR91mkNBBO8AwTXfzlsv3l4LDOWuu3aK9O3ZAM6rc8pHn167SIF8PUXKS1C9rPZBZBtk91JkHJiLKwAlKZBs7rEZCgnZAs47GGzGG78VAJ6glG0zFU1Eaf8qrjQTLEMutqSxXgTVysMqxTtrv83MITNPl6f9cnz
- page_id: '377394845467706'
  name: page_38
  display_name: Wu Tong's Family
  enabled: true
  drive_folder_id: 1DUewTYHyfLjT-IEKh0lsWbs30sHT-WiJ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSjuv49HhV7mCuYxND1QzGLNkDiiM8SQBrVnZCcjF0tSuqvZCbS6HGeNBRmpX1IWlZAQR5VHwMqlfkUaF8JDaKVZAZB9p3slK1dNavl5gyKL9svtHHMV6PgLkqnAEb1Bwg6dE9OxUIAgQfo11KouVsRZBWw9IVEolhyDoT2oCwKZANlxcdOZBodmmZCYITbp2u
- page_id: '301441593063746'
  name: page_39
  display_name: Prestige Authority
  enabled: true
  drive_folder_id: 1S-cw7Fe7G1GyvpYwH1RSe2vGJdC0_0Lm
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSqSYEAq4ICaX1dAmNVguitaDPGC714NZBJZBvAWK34teQwFD7w91Xv8ZAdSLZA8ZAoRS5iQyCN1HTvoZA1tQIPnZAOZB3duCMTDbxHiGb8ZAJedY2hkyZCy3zZAesCre1vpgZAMxJrZAs5YtziCmSDEu63XSVWll0fAZApwlZAPVPAYZAPcSU10c6VtXAOuCQi9mZCYR8
- page_id: '372905129232715'
  name: page_40
  display_name: Sthefany oliveira
  enabled: true
  drive_folder_id: 125WfzCXV4G8mtQfHa-9HxUeuIS_BXtYk
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSqmJ4h6r14rSARnHMXqzswM8grGi7rXmPaIg794ZAR3gNUT5i4NwoS7sXefYe16YZCyDFzK5DM8CcZA2WmOTpMfDHXwf93T3yR4NwojPbDOt3hR7wpsu1k4m9e9P4YH9OolcfZCMxJCZCx3JXBdHT0q3KGIyJDl40FZCaKby9iaaTrOVStxWZBgZCeYU6Eyw
- page_id: '271543462710279'
  name: page_41
  display_name: Iron Republic
  enabled: true
  drive_folder_id: 1h9B3ZNGqcWtRUD0-JhBBWCErlK8BsTbb
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSjbOl8pPJZCSMedqOQdZBWIiyP0y0q4MwRCqGwm8fAoyOTaaZCprTGXLRucxJpwPYMV0HovQq5oFpwVOZCoixveNpgTWSNc1uqbSETOU3AZANmJ6TAZAH8KjxSbj5G4UxjDcmc3csnnFsRvg26F8oq64QyLGrRYqXCzaWPPZB1evbYJvvY8YZCubyIkD2ewZD
- page_id: '209182608951563'
  name: page_42
  display_name: Shadow Executive
  enabled: true
  drive_folder_id: 1lK6PK14R0GGQRmk8lCA9L-ketOUFQbP6
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSsAjIquB2YXnN2nXcNeRB2HMz2D4WJHveXqQt9FhpfFKVp1htoOZCSYLFIh0U7pfYyo5TOn4wgs6eCUm7R3WBtR9Vt7Q7eFscbAUt7cCw3DKeJjPI8aPeh3OjROLDNei6FIWFMxbzMJf8sJljdpQh0T03WLvbl190ZC1WezWr7DM7ZAjuudSZAWrmzwZD
- page_id: '241688455685265'
  name: page_43
  display_name: Hu1
  enabled: true
  drive_folder_id: 1R9miZUECFxxSCVYjrLBUi23Hv6HhelYq
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSr2qzD0bKvsC73rKZAKw5X33XbZCouZAH9oieox2H2ZAFWB94K1XhmHG4mAsG9ZACPlHbRC4SOfo44gPSdfSen5mkOmZCLS5DdfGcZCaREfIZAgaP2QRIKbr4zKDCPegSRelAZBGza0s4SZBKTZCFaZBR1UFvIdiGHusfSOQWaFpfmdW6ObLQKyglfZB32g9lnvkZD
- page_id: '171465126060636'
  name: page_44
  display_name: Alpha Dynasty
  enabled: true
  drive_folder_id: 1OyrUqGKt0bPQqo6mekPjmAd2VJfb4CuQ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSo3EyeF8sIrYY96lepWNeOvFIpCZANO6kZBxhuWmw9rMdUvbFLQMAAe66N6cIpPRMazxHS2ZAe5XsIRKE1hgCo3wjs1Vcwn2sf3YH2tVTqfgauIx9Hvd2NykyLkIcbRAsyCcBfLzwQRa6AqiHWKMbn28qkIBbZCuuZCRC6mb1Rj11FQ9YuBlu9y5kCZA4ZD
- page_id: '160240527166280'
  name: page_45
  display_name: Path Summer
  enabled: true
  drive_folder_id: 1RPhbSb0nV7-yydSD-6m0kc12bhwAG4do
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSrbOO1SVZCnpl254LuizzeIiEelXGnZBuCPRtnR8eQQY4C72ZA5F4XL3aZA2wDVNCmcEZCvkHZAW86HzFg4qlX9a0m4axUljbFrRwZA6Ygj6vWoX4yCczdFP7uScZA3fMI5tl3ZAiX8Vn7dZBf3iriUR6ZC8bQQunJPBLSMLpNoS0nKHOZAJYpVWX9Cr8ZAafR6UZD
