page_group: uk_london_id_4_nidhi
account_name: Nidhi Desai
country_code: GB
target_location: London, England (EC2Y 8), United Kingdom
postal_code: EC2Y 8
require_uk_ip: true
ai_disclosure_status: pending_determination
delete_after_post: true
database:
  path: data/posted_videos.db
retry:
  max_attempts: 3
  base_delay_seconds: 5
  max_delay_seconds: 60
notifications:
  discord_enabled: false
  discord_webhook_url: ''
pages:
- page_id: '1076375522219372'
  name: uk4_page_1
  display_name: Titan Archive
  enabled: true
  drive_folder_id: 11qk-b66GAyO0NTvHX2TUKRiVsiK-Jk7e
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSlA6bZAKinUwH9OG7I44GktOZBN7tZBZAWvYWfVZBGBdB7fjDGPX6lj66AAVzQHbakEUKnwzJxklSzSZAiCpOmS8ZCBIugiWzzY7Ij0wjB7NEa5qzWrHNoLVszeQoWK4tr6ld2ZBGsjlDiSiwFflrp0AnDZByxh3ZCf4xAsZBLHUOZAsMxTHMu4Fw0GyCrK9
- page_id: '997596213442388'
  name: uk4_page_2
  display_name: Sovereign Signal
  enabled: true
  drive_folder_id: 1s4FC3XfpaCwLC8SjQc7ytMoXbxmW1sa1
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSsX5ROA3kNXmRPQZAFddRDDDj5leXI1ELKIHgFObRg1JA8nHYYcQrr36cqZAh3FvVzfOtDdpHtVdnzWVLJX1pGDtPHG9zxFTNPCnh93AS1Y4MzvzqZCpmjYDDktcloZCV0F5bfpgDYN3SRsZAWl3twitH6Ii7QveGWxSuMcboATUYKHgdGfsflNRp
- page_id: '1025542247301378'
  name: uk4_page_3
  display_name: Sunny Dusk Stories
  enabled: true
  drive_folder_id: 1lDezQeKpSXSOg5kafNTED2AMhAyrx4k0
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSl4s2vtM30iqIxpQNfExT2kO5F5GA3izlPxFcSLQ8R4ZCFngVyucpOsApZBnPr521sge46IzDB96sWn3ZCJrLjA9fQkK2h2Vt2lreda7vePoEeXraZCUzGOUkuhvtUMHN1Q1TZAwJijzbZAa1QSqK9ZA7s5Mb8e33597hj6vhPOBtGdmFIDEAnCRCpA
- page_id: '981214481738903'
  name: uk4_page_4
  display_name: Silver Oak Social
  enabled: true
  drive_folder_id: 15hPBojsrRBiBOR0331zGeuYxqOF4ambV
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSkMv82ZBlVQVFNMvsubA1NhZCtOw2lRHdnZAvi9DZCl6oB24HCIDpmT4vlVoHWrWxzqjryKLGH3tAK5nXDjE8mR5BCJpHmFORf1HtnCxnplQD0F9W1QURRJiksGHEemxtWZAil9zLU5ZBJLzRpRIZCVHLLO6SpZAD2J980oda0xw1h6TlcYGgHrRx8SH
- page_id: '929190903615356'
  name: uk4_page_5
  display_name: Mitchell  Gabriel
  enabled: true
  drive_folder_id: 1Y1wCJxMqCzWUh0YMPoh5KGG4YpEnqT6a
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSp5dbwqSSGzGcZBAdcXHZBhEyin075S6NQHpXv7caot5DfiJhjgX00pxXtlOYVPGpSt1yLMieA4R1lyiiAhZAwiN5wVkbIgawZA11BlFxqRZCuAOZCYsJb7MIVD4w0gCWZCKWausDYTOfGup97ZBo16xc6ZAx0DUWQZBCP8Hmbzvwewc7uJzgBRRYQh6vf
- page_id: '803824339488556'
  name: uk4_page_6
  display_name: Smith  Arthur
  enabled: true
  drive_folder_id: 14NWdo8WKfg9kH4OYGOcZJjCpr0MFXtXk
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSiSu88jeZCgdR9RufecmsvahOJ5vn8NgwiZAN59hZAUS5n2iUQtAAo4aeJqMddtiy3ovtL4IKqd0SzyfgP1sqW9La1zjZAda4AZBloMIZCoNwhsNHjukvxD9JTjBNdlQmuwhOJHPAd06zETHrF9orIFuNcsSuQAo5ZAkOWrUxwqH8WBE1T2gFp09Vbu
- page_id: '857530914106167'
  name: uk4_page_7
  display_name: Robinson  Jerry
  enabled: true
  drive_folder_id: 1t6HAdbjvYUMy2dTbtwFvip4n4trRpLs6
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSlmWxaSdpJhZAMGZBwZAvksfJ9a4y3KpZBrqRulMbclZAr0KMhkRvRA0krzKVT1ZByBfaZB4vg6siCwu86KOWC1WndI6dT4T6FU2JBZAZAzuq7AUFCAUzsLdJlSljhfZAeBi8WLxFT6fQn0WuQyBNwtVKAGOh6G4wnmhjPyBpmYmfW04Ed6A7Fz3QIjpyU
- page_id: '762765990263739'
  name: uk4_page_8
  display_name: Robinson  Stephen
  enabled: true
  drive_folder_id: 1iMpfR-mZdfljA1OjWOEjAMM9CtODCaLO
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSllvRDKud9iXRyr2H0T9s6AL8rqYUyLc2ZA3lcUxxHHzEBnIoW5pZAqfV44kQvbq77JryNMlsE04mipehx0EAHSxQot63LRS0BsHzAhSHFL1NpZArw1utVHfmUI8nGj7ZCGTWVrvRZADpKlukk1G2FZCqTb92LeamCYAtKipWSur9Sb8btYZAUZADbIL
- page_id: '871774779344742'
  name: uk4_page_9
  display_name: Powell  Gabriel
  enabled: true
  drive_folder_id: 1OgWhFRr1Tez6SJVDBTzJF8-BbFdG9Hgu
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSheot2wQJlvAjTgAVX1sbISPKfW8C40cvrptB8STsPW4x6XawFGzEyikZCQvVwWGAZA20LNZC0h0355DywKXtmUVbZBv4zE0TQKDDnnrb6k1RTjnzWhEh1AHBWxAUxtl9ZASxN68BxIcftlAXDeXJSwTlrZAAOQKfuyW3xV0VAZBNwPWTS59iw19hX8
- page_id: '746108741929454'
  name: uk4_page_10
  display_name: Rodriguez  Scott
  enabled: true
  drive_folder_id: 1Bbn4TxIRO-mshKSg7BPvTxHVgF59x8QL
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSoZBYpUdgZATjnBua8d1o5QuRZA9zvjib2uwr3FgZAmHIGITiuHtvxBXVnReQrFOFpuMZBpxTq1csgZAGMRRAnuPJ2MP4xsYtq2qlaIYevbI4uMmNTnQxngvkpWKnbtb7vajGtBEMfeZCwBPrntaAIrtWpnNho7BMJHY1HZAjOY7biTMIsErhJLsBdIT
- page_id: '818808074651170'
  name: uk4_page_11
  display_name: Roberts  Richard
  enabled: true
  drive_folder_id: 1Imakyr8eJJvH9YwJP6pTbozbTQFO_lWz
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSvzbTKomUvcWfjtpufFIEfiBgMHEIFuB7s2mBrapPhJhWiiloMci8YISgNYsguGvoavveGJisWcsOYocHur2Cz4SoHapHr7UVZBlZBq2BpecmVY3UL1Fj8ZBhK75WgLSDSaKeZAXVvQMoLT2KyqOktPTwML0GtxiTIGx9Ww6UOOEZAjeg8ucUe8Ax
- page_id: '417387901468629'
  name: uk4_page_12
  display_name: Serendipity Spark
  enabled: true
  drive_folder_id: 1gKXG4J5c2h_9Ioh8gUmRS1ytNVgNTK4s
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAT33ScZBmTcBSkjiDRrqMXHYCmMk9qREwzkIRZAH6CBe8B54I1JSvQlmG3gYeBon1OUxJiu9ZBRYou8GvFQjS1ZAih8T5QHt9nxaJad41sDZCTTzfdnExFGF325AZBFZBx8HgtYQZB124TPCTZCLMJCZBzuU6ZCzZCiPa9IWg75Ggpdk5BjoaVccGTB0ibSMATjKc1ZBIzdf
