page_group: usa_account_3_radika
account_name: Radika Patel
country_code: US
target_location: United States
require_uk_ip: false
ai_disclosure_status: pending_determination
delete_after_post: true
database:
  path: data/posted_videos.db
retry:
  max_attempts: 3
  base_delay_seconds: 5
  max_delay_seconds: 60
notifications:
  discord_enabled: false
  discord_webhook_url: ''
pages:
- page_id: '1033900793135926'
  name: page_31
  display_name: Cloud berry Lane
  enabled: true
  drive_folder_id: 1gtFrX3Ji1yjJ5f8yHe1zOcdgMCTDQFMn
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSvpXCAucVsnikObsXxy4y6BZBTCD7az2TVyED9yrhFgZBcqmB9RZA52YrZCnMB1d8gzWHhhajNYXBZCcxuKOZA2AObuZC4UOgyALPkEzhI2ZCxtUH5K7s1J8ZBYBXBZBgm0oJt5h6DWYMl8VGFWYUwywdc4gU5O3ZBvnbs4Fljimvkou1XrWLpiHQCZABzhW
- page_id: '984876688045322'
  name: page_32
  display_name: Sunset Mint Post
  enabled: true
  drive_folder_id: 1BURCLnzpluribfLIMlx7iPp-qdf_GL2T
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSo5169FD9DUO4BsCC2eAaTyCci9BcvHeX7ZB0WR9ExMeQSAT4pw3mkLe0njmVSTorXtIj6KKDdRc0I1soscUyol6TDJxEZAGKLwJKWguz5RItNlO8JfYIiZA1CPBuVt9vOawroyc3tf7UfNDOjbnRTZBZBa7EeMlrwGrqfAniGitpsFkXXJdtJwLY
- page_id: '928116440385651'
  name: page_33
  display_name: Timeless Glimpse
  enabled: true
  drive_folder_id: 1TcsGrKQd3ueOdVGgjsG5ujrwHmnoLd4N
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBStZAGEyAhhU8ONYjSoBHXKYwMO3MVYqpAdZA91t1VQzXoPn8O5T1TXWZA3PGftRlPcWWVZBxsTCfLAPhtT6bSovmeRF0HVziwPfGIdAYiZAnW0mQNviT8E3e6mKzeZBWJRZALZCZArckiLohZBQM4xWByZA1we5kZCich94Tm6DaCfJZAPrcu8URrRvpHadPF
- page_id: '495281633679562'
  name: page_34
  display_name: The Entertainment Zone
  enabled: true
  drive_folder_id: 1pBBPnxX539_8XbACP_xN5ZaqdgnVNdaC
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBShs9jPA0hko4nP43gekIIiCfx1Vn4yjrsLi0uTylRoDGVcVIsXQa7LvrzeZBufZCiqXLuq1pQuDwFzbFRLkyKHDwSK3RmCRC4V95WRUumrMZCXfnzZACpUVeOSusCEdoHmN8xdFxab2fIdjJEN3sZCHRXLRZBfZC9xxrJqroFHb4ZBzu1dlt9lC9uiDZA
- page_id: '461899523680517'
  name: page_35
  display_name: House Note
  enabled: true
  drive_folder_id: 1MMHC7iT-E1r-R8p-uSXY5_JJU5ttxhAp
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSobylImCIBM7MP8brqcT1yZCSRtLaWnZCs1AKn7PkCfZCTINvXZBmQYzZC03kQ9y1ScmebdZBMxtUetA3zJozd5bZCJB4Ib2CUfo4e2qzZB6UgKpMLj52BfYZApZCQ7pTya7z3Nz8hNmnMubHR5938bAQFxRb6iZCZC6ZCisZCT3kM91uwojQWfWiqpj5lehFP
- page_id: '512339515286069'
  name: page_36
  display_name: Wand Wizardry Legend
  enabled: true
  drive_folder_id: 12Z5ghscmqcwCCjqK4nE-AEa0ecwPmBxA
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSoyukgchShQZBWiSSc1WZBZCAr6twpOp62As3NMgi7RZBpPeJyASj8z9WkQwjXhDbOm4gU4u39G4Vtui3s0dBJLtIZCfHPI4HQe96bN8hlZCx43L70pJk4jO0FnpWntSX1ZAsZBJvIa2C24vFXLb8XEDmHdGK58rbMujXKB4vNAOVhO7dQyxHHyZCAHX1
- page_id: '481027178422627'
  name: page_37
  display_name: Potato Flamingo
  enabled: true
  drive_folder_id: 11EFX0WJ32MzLCMbtRU3cehqjmFLuQ3KC
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSqFjK8uUIZA222mO5r2ZAIKM0pv7Mgyi0oZBAIxJbnVy14scMzqpqZBz7MsGvUPUuuGkqLWnmGLmq3l6E58EZCakE5LstZA6HIAMzjZCHoHYNFvHS4VJdBSSvZBudxHR6kJ2WMhbOhMkP0gxDNh7TlpJvdcokwhVERAVxLC0j9rXrFOpAC4ORIbenhcx
- page_id: '377394845467706'
  name: page_38
  display_name: Wu Tong's Family
  enabled: true
  drive_folder_id: 1DUewTYHyfLjT-IEKh0lsWbs30sHT-WiJ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSo1uXTpGKLkdWy0q2SaHNNWtcUJZCmJeZAIzkSHyaUl01UJbPiqtDqZCDpQs8BF1VLlD29dRJ7qZApUebucPuaYcBpMFbEZAV9cjcaDcsrc2nCAAmLMjebJrc0lS7TSxwELK0aMimVbDnjGIsFietgTHotIoEoV9qoloY8qOcpKsQfhlISxrnpTK7
- page_id: '301441593063746'
  name: page_39
  display_name: Prestige Authority
  enabled: true
  drive_folder_id: 1S-cw7Fe7G1GyvpYwH1RSe2vGJdC0_0Lm
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSkQKL0PLrHLzm22x9S091T59YY8qjF5rnlJvJpN5WnLYPPKFU0F1pNKrGXgjrPQ56lDS9eHjetn1Eoju4v4VOMvZC5jWXEvhwbNFPJQ337TL1ZCGBGJLGhAkMUz6GY169bZB2sZBz7Kv9ZCZCJ7UZBSIDbL6MG0zAsvq8UwcbJdZBKbe7jfxUZCgbIdvA
- page_id: '372905129232715'
  name: page_40
  display_name: Sthefany oliveira
  enabled: true
  drive_folder_id: 125WfzCXV4G8mtQfHa-9HxUeuIS_BXtYk
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSp6KewZAk6EZA2kLFojpc2NH0l73cJZArZA1GC2ZAJOw6Buh02oP6hWpzhaDr8mazeVx6MZAnBjTFfFQn8nQnlv9duFopeplz625KZAEuHTdCvemVspZCMEnkGInCZANhbuXbYyBsH5btYGLZB7CRbiI5h8apEoLp6h4p0170EUw2pzJ5by1GZAEiZAYZBbFQ
- page_id: '271543462710279'
  name: page_41
  display_name: Iron Republic
  enabled: true
  drive_folder_id: 1h9B3ZNGqcWtRUD0-JhBBWCErlK8BsTbb
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSjUjWH0E8qt54VFywvqXYvWNLLxS20rEIr0ADZA7N7dqIoq5Ph8aJYHpppeU7PlfmCdWvYC7QH4KBK5pdiNTzbHZAhcARnAgPtB7PIR7YoUZB7jrna2Yi4rUBZBssFta9nVf1gZA8pZCgwB8qxQOpti9IZCFqohCZBgHebr5WO1NwoisWS8MZAz2lM6UZD
- page_id: '209182608951563'
  name: page_42
  display_name: Shadow Executive
  enabled: true
  drive_folder_id: 1lK6PK14R0GGQRmk8lCA9L-ketOUFQbP6
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSjEcUKDbDTcTlSSBpzWa6ipBlh6h0QLQdISWmIWAae5S42yUKw4QIGtEqJ2woVG3unsPuhvitUH3TVWXOVQFbg6ToeQUSy4aw9ZCL11U9HKjBj6JL6kWVmOEKHK3DmDjXrXZCHisdQsTONxwGB4BvWfifUkEj0XZBeYTt2jeG9ZAOcZBoYR0z2PkZD
- page_id: '241688455685265'
  name: page_43
  display_name: Hu1
  enabled: true
  drive_folder_id: 1R9miZUECFxxSCVYjrLBUi23Hv6HhelYq
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSsDzH3aDIoSMzfCfp3RVwv2V73OG0OtJLWLqUd09C6nxQjXzlxZAkWpaH7qy6SAZAFckgT8tqoxNBrCXeZC38q9JtErZBffR3fLZBFqgDUQeScf1uhL1Ej9I1a9wi3BqqxeFHBbGfHHtoeLDiYDiUaYD9J4GyZCLnTU3TKlDPmMfp9ZBJWMU7wwQ08ZD
- page_id: '171465126060636'
  name: page_44
  display_name: Alpha Dynasty
  enabled: true
  drive_folder_id: 1OyrUqGKt0bPQqo6mekPjmAd2VJfb4CuQ
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSuAjU05xvVBNz7RZAman5a9pRmUQl5dJ6UY0ZAvibnREQd7pZCJ5J7IJBGslQbJRvgYFrEoxhZAoQlNe8bgQ0vxCvB0LjIWvdeGaXyWU6u2t3QdLCZCB8ZBrQI2Da32IqZAH3xnJA2dsKlNRhLJZAPDmD9J5ZBCIMHAmMRpe7qGSK9KlRJxE1QodP8acZD
- page_id: '160240527166280'
  name: page_45
  display_name: Path Summer
  enabled: true
  drive_folder_id: 1RPhbSb0nV7-yydSD-6m0kc12bhwAG4do
  daily_limit: 4
  title_mode: filename
  description_footer: ''
  default_hashtags: []
  page_access_token: EAAPVZAF121dYBSqBNhZCsW5qMPEKK96FdJzy27NVRoLGn3PVqojU2WAe4n72IIPHXLyZCgAZAwZBZAraIryG2r3nvzQyP8I0JDiVCOL8sdc6JNyYEO4fQCSxiIhLLSFq8nStZByJJV3sM2DHQJV2bajNKEaZBDK0YEbqnFs9ZASDOij3InKjGLmNd9dQQl5BWFsnE95MZD
